.TH UNDELETE 1
.SH NAME
undelete \- undelete a file
.SH SYNOPSIS
\fBundelete\fR [\fIfile\fR]\fR
.br
.de FL
.TP
\\fB\\$1\\fR
\\$2
..
.de EX
.TP 20
\\fB\\$1\\fR
# \\$2
..
.SH EXAMPLES
.TP 20
.B undelete infile >outfile
# Undelete \fIinfile\fR
.SH DESCRIPTION
.PP
\fIUndelete\fR undeletes a deleted file
